# This script is generated by ChatGPT
# This script has following functions:
# 1.Extracts the markdown tables from the "response" key in the JSON files output by Project_2_1-ExtractInformationFromJSON.py
# 2.Merge the markdown tables to one table.
# 3.Output the table to a Excel file.
import json
import pandas as pd
from pathlib import Path
import os

# Function to extract and parse markdown tables from a JSON file
def extract_and_parse_tables(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)

    pii = Path(file_path).stem

    tables = []
    for item in data:
        if 'response' in item and '|' in item['response']:
            markdown = item['response']
            lines = markdown.split('\n')

            # Finding the header row (assuming it contains '---')
            header_line_index = next((i for i, line in enumerate(lines) if '---' in line), None)
            if header_line_index is not None:
                headers = lines[header_line_index - 1].split('|')[1:-1]
                headers = [header.strip() for header in headers]
                headers.append('PII of the source paper')

                rows = []
                for line in lines[header_line_index + 1:]:
                    if '|' in line:
                        values = line.split('|')[1:-1]
                        values = [value.strip() for value in values]
                        values.append(pii)
                        if len(values) == len(headers):
                            rows.append(values)

                if rows:
                    df = pd.DataFrame(rows, columns=headers)
                    tables.append(df)

    return tables

# Specify the folder path where your JSON files are stored
folder_path = 'path/to/JSON/files'  # Replace with your folder path
output_folder='output/path'
# Listing all JSON files in the folder
file_paths = [os.path.join(folder_path, file) for file in os.listdir(folder_path) if file.endswith('.json')]

# Extracting, parsing, and merging tables from all files
all_tables = []
for file_path in file_paths:
    tables = extract_and_parse_tables(file_path)
    all_tables.extend(tables)

# Merging all tables into one
merged_table = pd.concat(all_tables, ignore_index=True) if all_tables else pd.DataFrame()

# Cleaning up the merged table
cleaned_table = merged_table[~merged_table['Lithium Metal Oxide Name'].str.contains('------------------')]
cleaned_table = cleaned_table[cleaned_table['Lithium Metal Oxide Name'].str.strip() != '']

# Deleting rows where 'Numeric Value' is blank, '-' or '/'
cleaned_table = cleaned_table[~cleaned_table['Numeric Value'].isin(['', '-', '/','N/A'])]

# Outputting the cleaned table to an Excel file in the specified folder
output_file_path = os.path.join(output_folder, 'outputfile.xlsx')
if not cleaned_table.empty:
    cleaned_table.to_excel(output_file_path, index=False)
    print(f"\nCleaned data has been saved.\n")
else:
    print("No data available in the tables to save.")









#folder_path = './DemoForExtractingTablesFromResponseKeys'
