#This script is generated by ChatGPT
#The function of this script:
#1. Read image files and their page number;
#3. Extract the information of LMO in the image using GPT-4 API.
import os
import base64
from PIL import Image
import pandas as pd
import time
import logging
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv
import io
# clear the screen
os.system("cls")

# Setup logging
start_time = datetime.now()
current_time=start_time.strftime("%Y%m%d_%H%M%S")
log_filename = f'./A3.Logs/log_{current_time}.log'
logging.basicConfig(filename=log_filename, level=logging.INFO, format='%(asctime)s %(message)s')
logging.info(f"Script started at {start_time}")
print(f"-----------------Script started at {start_time}-----------------")

#Setup API key and proxy
load_dotenv('./API_key.env')
#API_key.env content
#OPENAI_API_KEY=your_api_key
#set proxy if necessary
#proxy_url = 'your_url'
#proxy_port = 'your_port'
#os.environ['http_proxy'] = f'{proxy_url}:{proxy_port}'
#os.environ['https_proxy'] = f'{proxy_url}:{proxy_port}'
client=OpenAI()
# Path to the folder containing PDF files
paper_path = 'path/to/image/folder'
output_folderpath='/output/path'

def encode_image(image_path):
    with Image.open(image_path) as img:
        buffered = io.BytesIO()
        img.save(buffered, format="JPEG")
        return base64.b64encode(buffered.getvalue()).decode('utf-8')

def process_folder(folder_path):
    images = []
    for filename in os.listdir(folder_path):
        if filename.endswith(".jpg"):  # Adjust the file extension as needed
            file_path = os.path.join(folder_path, filename)
            encoded_image = encode_image(file_path)
            images.append({
                'PaperName': os.path.basename(folder_path),
                'PageNumber': filename,
                'Image': encoded_image
            })
    return pd.DataFrame(images)

def call_openai_api(dataframe):
    responses = []
    token_count = 0
    request_count = 0
    total_pages = len(dataframe)
    for index, row in dataframe.iterrows():
        prompt="""
        Your prompt
        """
        
        if token_count + len(prompt) > 800000 or request_count >= 10000:
            logging.info("Token or request limit reached, sleeping for 60 seconds.")
            time.sleep(60)  # Wait for 1 minute
            token_count = 0
            request_count = 0
        
        response = client.chat.completions.create(
                model='gpt-4-turbo',
                messages=[{"role": "system", "content": "You are a helpful assiatant."},
                            {"role":"user",
                             "content": [
                                 {"type": "text", "text": prompt},
                                 {"type": "image_url", 
                                  "image_url":{"url":f"data:image/jpeg;base64,{row['Image']}"},
                                  },
                                  ],
                                  },
                        ],
                temperature=0  # Modify the prompt as per your specific requirement
        )
        print(f"Complete: {row['PageNumber']}     Progress:{index+1}/{total_pages}")
        token_count += len(prompt)
        request_count += 1        
        result = response.choices[0].message.content        
        responses.append({
            'PaperName': row['PaperName'],
            'PageNumber': row['PageNumber'],            
            'Response': result
        })
    ReponseDataFrame = pd.DataFrame(responses)    
    return ReponseDataFrame

def save_to_json(dataframe, folder_path, file_name):
    output_path = os.path.join(folder_path, f'{file_name}.json')
    dataframe.to_json(output_path, orient='records', lines=True)

def main():
    base_folder = paper_path
    total_files = len(os.listdir(base_folder))
    processed_files = 0
    for folder in os.listdir(base_folder):
        folder_path = os.path.join(base_folder, folder)
        if os.path.isdir(folder_path):
            df_images = process_folder(folder_path)
            if not isinstance(df_images, pd.DataFrame):
                raise ValueError("Expected DataFrame but received a different datatype.")
            print(f"Extracting:{folder}")
            df_responses = call_openai_api(df_images)            
            if not isinstance(df_responses, pd.DataFrame):
                raise ValueError("Expected DataFrame but received a different datatype.")
            save_to_json(df_responses, output_folderpath, os.path.basename(folder_path))
        processed_files+=1
        logging.info(f"Complete:{folder}    Progress: {processed_files}/{total_files}\n=========================================================================================")
        print(f"Complete:{folder}           Progress:{processed_files}/{total_files}\n==============================================================================================")

if __name__ == '__main__':
    main()
end_time = datetime.now()
print("----------------------------------------------------------------------------------------------")
logging.info(f"Script ended at {end_time}")
logging.info(f"Total runtime: {end_time - start_time}")
