#This script is generated by ChatGPT. This script searches and downloads papers in JSON files using Elsevier Text Mining API
from elsapy.elsclient import ElsClient
import json
import requests

## Load configuration
#Configuration file content:
#{
#    "apikey": "your api key aquired from website: Elsevier developer portal",
#    "insttoken": "your institution token aquired from Elsevier"
#}
con_file = open("config.json")
config = json.load(con_file)
con_file.close()

## Initialize client
client = ElsClient(config['apikey'])
client.inst_token = config['insttoken']
base_url = "https://api.elsevier.com/content/search/sciencedirect"
headers = {
    'X-ELS-APIKey':config['apikey'],
    'X-ELS-Insttoken' : config['insttoken'],
    'Accept':'application/json'
}
def download_full_text_pii(pii, api_key,ins_token):
    global successful_downloads, failed_downloads
    download_url = f"https://api.elsevier.com/content/article/pii/{pii}?httpAccept=application/json"
    download_headers = {'X-ELS-APIKey': api_key, 'X-ELS-Insttoken' : ins_token,'Accept': 'application/json'}
    response = requests.get(download_url, headers=download_headers)
    
    if response.status_code == 200:
        with open(f'./downloadpath/{pii}.json', 'wb') as file:
            file.write(response.content)
        successful_downloads += 1
        print(f"Downloaded full text for PII: {pii}, {successful_downloads} papers have been downloaded")
        
    else:
        print(f"Error downloading full text for PII: {pii}: {response.text}")
        failed_downloads += 1

total_papers = 0
successful_downloads = 0
failed_downloads = 0
start_paper = 51  # Starting from the 1000th paper
end_paper = 100   # Ending at the 1050th paper
count = 50          # Number of papers to fetch per request
offset = start_paper - 1

while total_papers + offset < end_paper:
    
    params={
        'date':2024,
        'display':{
            'highlights': False,
            'offset':offset,
            'show':count,
            'sortBy':'relevance'
        },
        'filter':{
            "openAccess": True
        },
        'pub':" Energy",
        'qs':'(lithium diffusion coefficient) AND (density function theory) AND (lithium ion battery) NOT ("Electrochemical measurement" OR "Electrochemical characterization" OR "material characterization") NOT ("state of charge") NOT ("state of health")',
        'title':"-review -progress -recent -challenge -developments -perspectives -advance"
    }

    # Execute Search
    try:
        response = requests.put(base_url, headers=headers, json=params)
        search_results = response.json()        
        papers = search_results.get("results")
        print(search_results.get("resultsFound"))
            
        
        if not papers:
            break  # Break the loop if no more papers are found

        # Extract Full Texts
        for paper in papers:
            pii = paper.get('pii')
            if pii:
                try:
                    download_full_text_pii(pii, config['apikey'],config['insttoken'])
                except Exception as e:
                    print(f"Exception occurred while downloading PII: {pii}: {e}")
                    failed_downloads += 1
            else:
                print(f"No PII found for paper: {paper.get('dc:title', 'Unknown')}")
                failed_downloads += 1

        total_papers += len(papers)
        offset += count
    except Exception as e:
        print(f"Error executing search: {e}")
        break

# Summary
print(f"Total Papers: {total_papers}")
print(f"Successfully Downloaded: {successful_downloads}")
print(f"Failed to Download: {failed_downloads}")