#This script is generated by ChatGPT
#The function of this script:
#1. Read full text of the papers from source JSON files;
#2. Segment full text of the papers to paragraphs according to the chapter name;
#3. Extract the information of LMO in the text using GPT-4 API.
import logging
from openai import OpenAI
import os
import pandas as pd
import json
import re
from datetime import datetime
import time 
from dotenv import load_dotenv
class APITooManyRequestsError(Exception):
    pass    
# Setting up logging
directory_path = 'path/to/JSON/files/of/the/papers'  # Replace with your actual directory path
file_names = os.listdir(directory_path)  # List all files in the directory
output_dir = 'path/to/output/path'
# Create output directory if it doesn't exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
start_time = datetime.now()
current_time=start_time.strftime("%Y%m%d_%H%M%S")
log_filename = f'./path/to/log/files/log_{current_time}.log'
logging.basicConfig(filename=log_filename, level=logging.INFO, format='%(asctime)s %(message)s')
logging.info(f"Script started at {start_time}")
print(f"-----------------Script started at {start_time}-----------------")
load_dotenv('./API_key.env') 
#API_key.env content
#OPENAI_API_KEY=your_api_key

#set proxy if necessary
#proxy_url = 'your_url'
#proxy_port = 'your_port'
#os.environ['http_proxy'] = f'{proxy_url}:{proxy_port}'
#os.environ['https_proxy'] = f'{proxy_url}:{proxy_port}'

# Function to extract text from a JSON file
def extract_text_from_json(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            data = json.load(file)
            original_text = data['full-text-retrieval-response']['originalText']
            return original_text
    except Exception as e:
        return f"Error: {str(e)}"
# Simplified segmentation function
def simplified_segmentation(text):
    # Define the keywords and their variations
    keywords = [
        'Introduction', 
        'Experimental section', 'Experimental', 'Materials and methods', 'Methods',
        'Results and discussion',
        'Conclusion'
    ]

    # Regular expression pattern to find sections
    pattern = '|'.join([re.escape(kw) for kw in keywords])
    segments = re.split(f"({pattern})", text)

    # Initialize variables
    segmented_text = []
    current_section = 'Unknown'

    # Process each segment
    for segment in segments:
        if segment in keywords:
            # If the segment is a keyword, update the current section
            current_section = segment
        else:
            # Add the text segment
            if segment.strip():
                segmented_text.append((current_section, segment.strip()))
            current_section = 'Unknown'

    return segmented_text
# Function to interact with GPT-4 API
def interact_with_gpt4(content, prompt_template, token_count, request_count):
    try:
        client=OpenAI()
        prompt = prompt_template.replace("{text content}", content)

        # Check for token and request limits
        if token_count + len(prompt) > 450000 or request_count >= 10000:
            logging.info("Token or request limit reached, sleeping for 60 seconds.")
            time.sleep(60)  # Wait for 1 minute
            token_count = 0
            request_count = 0

        response = client.chat.completions.with_raw_response.create(
            model="gpt-4-1106-preview",
            messages=[{"role": "system", "content": "You are a helpful assistant."}, 
                      {"role": "user", "content": prompt}]
            
        )
        
        token_count += len(prompt)
        request_count += 1
        completion = response.parse()
        return completion.choices[0].message.content.strip(), token_count, request_count
    except Exception as e:
        logging.error(f"Error in GPT-4 interaction: {str(e)}")
        return f"Error: {str(e)}", token_count, request_count

def process_and_save_final_result(file_path, prompt_template, output_dir):
    file_name = os.path.basename(file_path)
    content = extract_text_from_json(file_path)

    if not isinstance(content, str):
        logging.error(f"Invalid content in file: {file_name}")
        return None, None, 0

    segmented_texts = simplified_segmentation(content)
    final_result = []
    token_count = 0
    request_count = 0
    for section, text in segmented_texts:
        response, token_count, request_count= interact_with_gpt4(text, prompt_template, token_count, request_count)
        final_result.append({'file name': file_name, 'section name': section, 'content': text, 'response': response})
    df = pd.DataFrame(final_result)
    
    # Save to JSON file
    output_file_path = os.path.join(output_dir, file_name)
    df.to_json(output_file_path, orient='records')
    return token_count
#End part used in the end of the script
def end_part_of_script(start_time,latest_token_count):
    end_time = datetime.now()
    logging.info(f"Script ended at {end_time}")
    logging.info(f"Total runtime: {end_time - start_time}")
    if latest_token_count is not None:
        logging.info(f"Tokens used in this session: {latest_token_count}")
    print(f"Total runtime: {end_time - start_time}\n")


prompt_template = """Your prompt
{text content}
"""  # Replace with your actual prompt


latest_token_count = 0
total_files = len(file_names)
processed_files = 0
try:
    for file_name in file_names:
        file_path = os.path.join(directory_path, file_name)
        token_count = process_and_save_final_result(file_path, prompt_template, output_dir)
        latest_token_count = token_count
        processed_files += 1
        logging.info(f"Complete:{file_name}    Progress: {processed_files}/{total_files}\n=========================================================================================")
        print(f"Complete:{file_name}           Progress:{processed_files}/{total_files}")
    print("----------------------------------------------------------------------------------------------")
    end_part_of_script(start_time, latest_token_count)#Origin script: end_part_of_script(start_time, latest_remaining_requests,latest_remaining_tokens,latest_token_count,time_before_tokens_reset)
except APITooManyRequestsError as e:
    logging.error(f"Script terminated early due to API limit: {str(e)}")
    print("----------------------------------------------------------------------------------------------")
    print(f"Script terminated early due to API limit: {str(e)}")
    end_part_of_script(start_time, latest_token_count)



