# This scipt is generated by ChatGPT
# The function of this script is:
# 1. Print the unqiue entries in the LMO name column on the screen
# 2. After research select between 0 and 1, the entries with the print LMO name 
#    are moved to result Excel file if 1, to delete table if 0.
import pandas as pd
import os

def process_excel_file(file_path):
    try:
        # Read the Excel file
        df = pd.read_excel(file_path)

        # Get unique values in "Lithium Metal Oxide Name" column
        unique_values = df['Lithium Metal Oxide Name'].unique()

        # Create empty DataFrames for ResultTable and DeleteTable
        result_df = pd.DataFrame(columns=df.columns)
        delete_df = pd.DataFrame(columns=df.columns)

        # Total number of unique values
        total_values = len(unique_values)
        
        # Iterate over unique values
        for index, value in enumerate(unique_values, start=0):
            # Filter rows with the unique value
            rows = df[df['Lithium Metal Oxide Name'] == value].copy()

            # Print remaining values to handle            
            remaining_values = total_values - index            
            print(f"Number of material remaining: {remaining_values}")
            print("-----------------------------------------------------------------")
            # Print material name and PII of source paper of the first row
            first_row = rows.iloc[0]
            print(f"Should the material be moved? 0 for no, 1 for yes.\n\nMaterial name: {value}\n\nPII of source paper: {first_row['PII of the source paper']}")

            # Wait for user input
            move_input = input().strip().lower()
            
            if move_input == '1':
                # Ask if additional information should be added
                print("-----------------------------------------------------------------")
                print("Should any information be added?")

                add_info_input = input().strip().lower()
                
                if add_info_input == '1':
                    # Ask for the information to be added
                    print("-----------------------------------------------------------------")
                    print("What information should be added?")

                    additional_info = input().strip()
                    # Use loc to set the value
                    rows_index = rows.index
                    df.loc[rows_index, 'Parameter'] = additional_info

                # Add all rows with the unique value to ResultTable
                result_df = result_df.append(df.loc[rows.index])
            elif move_input == '0':
                # Add all rows with the unique value to DeleteTable
                delete_df = delete_df.append(rows)
            
            # Clear the screen            
            os.system("cls")

        # Save the ResultTable and DeleteTable to Excel files
        result_df.to_excel('./ResultTable.xlsx', index=False)
        delete_df.to_excel('./DeleteTable.xlsx', index=False)

        return "Processing complete. ResultTable.xlsx and DeleteTable.xlsx have been created."

    except Exception as e:
        return f"An error occurred: {e}"

# Path to the provided Excel file
file_path = './cleaned_data.xlsx'
os.system("cls")
# Call the function to process the file
process_excel_file(file_path)
