# The script is generated by ChatGPT
# The function of this script:
# Rename the PDF papers with their DOI that is read from the first page of the papers
import fitz  # PyMuPDF
import os
import re
os.system("cls")
def extract_doi(pdf_path):
    with fitz.open(pdf_path) as doc:
        page = doc[0]  # Only the first page
        text = page.get_text()
    doi_match = re.search(r"(10\..+?/.+?)($|\s)", text)
    if doi_match:
        return doi_match.group(1).replace("/", "_")  # Replace slashes to prevent directory issues
    else:
        return None

def rename_pdf_with_doi(pdf_folder_path):
    for pdf_file in os.listdir(pdf_folder_path):
        if pdf_file.endswith(".pdf"):
            pdf_path = os.path.join(pdf_folder_path, pdf_file)
            doi = extract_doi(pdf_path)
            if doi:
                new_name = doi.replace(".", "_") + ".pdf"
                new_path = os.path.join(pdf_folder_path, new_name)
                try:
                    os.rename(pdf_path, new_path)
                    print(f"Renamed '{pdf_file}' to '{new_name}'")
                except OSError as e:
                    print(f"Error renaming '{pdf_file}' to '{new_name}': {e}")
            else:
                print(f"DOI not found in '{pdf_file}'")

# Specify the path to the folder containing your PDFs here
pdf_folder_path = "path/to/PDF/files"
rename_pdf_with_doi(pdf_folder_path)
