# This script is generated by ChatGPT
# The function of this script:
# Convert PDF papers to image files. One PDF for one folder.
import fitz
import os

def pdf_to_images(pdf_path):
    # Extract the base name of the PDF file (without extension)
    pdf_name = os.path.splitext(os.path.basename(pdf_path))[0]
    
    # Create a directory for the extracted images
    if not os.path.exists(pdf_name):
        image_folders_path="path/to/image/file/folder"
        os.chdir(image_folders_path)
        os.makedirs(pdf_name)
        project_path='path/to/project/where/the/PDF/folder/is'
        os.chdir(project_path)
    
    # Open the PDF file
    document = fitz.open(pdf_path)

    
    # Iterate through each page
    for page_num in range(len(document)):
        # Get the page
        page = document.load_page(page_num)
        
        # Render the page to an image
        pix = page.get_pixmap(dpi=300)
        
        # Define the image path
        image_path = os.path.join("path/to/image/file/folder",pdf_name, f"{page_num + 1}.jpg")
        
        # Save the image
        pix.save(image_path)
    
    # Close the document
    document.close()

def convert_pdfs(pdf_directory):
    # List all PDF files in the specified directory
    for pdf_file in os.listdir(pdf_directory):
        if pdf_file.endswith(".pdf"):
            pdf_path = os.path.join(pdf_directory, pdf_file)
            pdf_to_images(pdf_path)
            print(f"Converted: {pdf_file}")

# Specify the directory containing the PDF files
pdf_directory = 'path/to/PDF/files'

# Convert all PDFs in the specified directory
convert_pdfs(pdf_directory)
